language: python

python: 3.6
node_js: 0.10

install:
  - pip install -r requirements.txt
  - npm install -g serverless

script:
  - coverage run --source dynamicdns --branch --omit "*/__init__.py" -m unittest discover
  - sls version

after_success:
  - codecov -t $CODECOV_TOKEN