language: python

python: 3.6
node_js: 0.10

install:
  - pip install -r requirements.txt
  - npm install -g serverless
  - npm install

script:
  - coverage run --source dynamicdns --branch --omit "*/__init__.py" -m unittest discover
  - sls deploy

after_success:
  - codecov -t $CODECOV_TOKEN