language: python

python: 3.6
node_js: 0.10

install:
  - make install

script:
  - make codecov

deploy:
  - provider: script
    skip_cleanup: true
    script: make deploy-dev
    on:
      tags: true
      condition: $TRAVIS_TAG =~ !(^v[0-9]+\.[0-9]+\.[0-9]+)
  - provider: script
    skip_cleanup: true
    script: make deploy-prod
    on:
      tags: true
      condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+