language: python

python: 3.6
node_js: 0.10

install:
  - make install

script:
  - make codecov

deploy:
  - provider: script
    skip_cleanup: true
    script: make set-vars-from-dev; make deploy
    on:
      tags: true
