custom:
  version: v1
  stage: ${opt:stage, 'dev'}
  config: ${file(config/serverless-${self:custom.stage}.config.yml)}
  customDomain:
    domainName: ${self:custom.config.apiDomainName}
    basePath: dynamicdns-${self:custom.version}
    stage: ${self:custom.stage}
    certificateName: ${self:custom.config.apiDomainCertificateName}
    createRoute53Record: true
  pythonRequirements:
    dockerizePip: non-linux

service: dynamicdns-${self:custom.version}

package:
  exclude:
    - ./**
  include:
    - dynamicdns/**
    - config/**
    
provider:
  name: aws
  runtime: python3.6
  stage: ${self:custom.stage}
  environment:
    CONFIG_S3_REGION: ${self:custom.config.s3Region}
    CONFIG_S3_BUCKET: ${self:custom.config.s3Bucket}
    CONFIG_S3_KEY: ${self:custom.config.s3Key}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
        - route53:*
      Resource:
        - "arn:aws:s3:::${self:custom.config.s3Bucket}/*"
        - "arn:aws:route53:::hostedzone/*"

functions:
  test:
    handler: dynamicdns/aws/functions/test.handle
    events:
      - http:
          path: test/version
          method: get
      - http:
          path: test/myip
          method: get
      - http:
          path: test/dns
          method: post
      - http:
          path: test/script
          method: get
  version:
    handler: dynamicdns/aws/functions/version.handle
    events:
      - http:
          path: version
          method: get
  myip:
    handler: dynamicdns/aws/functions/myip.handle
    events:
      - http:
          path: myip
          method: get
  dns:
    handler: dynamicdns/aws/functions/dns.handle
    events:
      - http:
          path: dns
          method: post

  script:
    handler: dynamicdns/aws/functions/script.handle
    events:
      - http:
          path: script
          method: get

plugins:
  - serverless-python-requirements
  - serverless-domain-manager
  - serverless-aws-alias